### ISSUE TITLE
Add validation to nested resources in traits and resource types

### ISSUE THREAD

**Issue by eleonoraortega** [mulesoft-labs/rajapa#24]
As neither resource types nor traits are allowed to incorporate nested resources

The following example must be validated:
# %RAML 1.0

title: Example API
version: v1
resourceTypes:
  hasGroups:
    get:
    patch:
    delete:
    /groups:
traits:
 hasGroups:
    get:
    patch:
    delete:
    /groups:

**Comment by svacas** [comment]
could you fix the indentation pls

**Comment by svacas** [comment]
fixed by c0337e725c9f65f796bba2aeca53e26ebf898ecb

**Comment by eleonoraortega** [comment]
ok
