### ISSUE TITLE
Add support for date type representations

### ISSUE THREAD

**Issue by eleonoraortega** [mulesoft-labs/rajapa#31]
Date

The following date type representations MUST be supported:

**Type          Description:**
date-only:          the "full-date" notation of RFC3339, namely yyyy-mm-dd (no implications about time or  
                        timezone-offset)
time-only:        the "partial-time" notation of RFC3339, namely hh:mm:ss[.ff...](no implications about date        
                        or timezone-offset)
datetime-only:  combined date-only and time-only with a separator of "T", namely yyyy-mm-  
                        ddThh:mm:ss[.ff...](no implications about timezone-offset)
datetime:           a timestamp, either in the "date-time" notation of RFC3339, if format is omitted or is set to  
                        rfc3339, or in the format defined in RFC2616, if format is set to rfc2616

**Comment by fededonna** [comment]
done
