### ISSUE TITLE
Add validation for enums

### ISSUE THREAD

**Issue by eleonoraortega** [mulesoft-labs/rajapa#32]
The parser does not validate any invalid enum example.

Use the following example:
# %RAML 1.0

title: My API With Enums
types:
  country:
    type: string
    enum: [ usa, rus ]
    example: lala
  sizes:
    type: number
    enum: [ 1, 2, 3 ]
    example: 5

**Comment by fededonna** [comment]
:+1:

**Comment by eleonoraortega** [comment]
ok
